apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: abdulovdb/front
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        resources:
          requests:
            cpu: "250m"  # Запрашиваемое количество CPU
            memory: "512Mi"  # Запрашиваемое количество памяти
          limits:
            cpu: "500m"  # Максимальное количество CPU
            memory: "1Gi"  # Максимальное количество памяти
---
apiVersion: v1
kind: Service
metadata:
  name: front
spec:
  selector:
    app: front
  ports:
    - protocol: TCP
      port: 84 #порт для обращения
      targetPort: 3000 #порт на котором работает фронт
  type: LoadBalancer
