apiVersion: apps/v1
kind: Deployment
metadata:
  name: sympathy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sympathy
  template:
    metadata:
      labels:
        app: sympathy
    spec:
      containers:
      - name: sympathy
        image: abdulovdb/sympathy
        env:
        - name: PORT
          value: "4002"
        - name: POSTGRES_DB
          value: "sympathy"  # Если это ваша база данных
        - name: POSTGRES_USER
          value: "postgres"  # Имя пользователя
        - name: POSTGRES_PASSWORD
          value: "0896"  # Пароль
        - name: POSTGRES_HOSTNAME
          value: "postgres"  # Имя сервиса PostgreSQL
        - name: ISLOCALDEV
          value: ''
        resources:
          requests:
            cpu: "250m"  # Запрашиваемое количество CPU
            memory: "512Mi"  # Запрашиваемое количество памяти
          limits:
            cpu: "500m"  # Максимальное количество CPU
            memory: "1Gi"  # Максимальное количество памяти
---
apiVersion: v1
kind: Service
metadata:
  name: sympathy
spec:
  selector:
    app: sympathy
  ports:
    - protocol: TCP
      port: 82 #порт для обращения
      targetPort: 4002 #порт на котором работает сервис fastifty
  type: LoadBalancer
