apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: users:prod
        ports:
        - containerPort: 4000
        env:
        - name: PORT
          value: "4000"
        - name: POSTGRES_DB
          value: "users"  # Если это ваша база данных
        - name: POSTGRES_USER
          value: "postgres"  # Имя пользователя
        - name: POSTGRES_PASSWORD
          value: "0896"  # Пароль
        - name: POSTGRES_HOSTNAME
          value: "postgres"  # Имя сервиса PostgreSQL
        - name: ISLOCALDEV
          value: ''
        resources:
          requests:
            cpu: "250m"  # Запрашиваемое количество CPU
            memory: "512Mi"  # Запрашиваемое количество памяти
          limits:
            cpu: "500m"  # Максимальное количество CPU
            memory: "1Gi"  # Максимальное количество памяти
---
apiVersion: v1
kind: Service
metadata:
  name: users
spec:
  selector:
    app: users
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  type: NodePort
